services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: moodfood
    container_name: moodfood-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - moodfood-network

  webserver:
    image: nginx:alpine
    container_name: moodfood-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - moodfood-network

  db:
    image: mysql:8.0
    container_name: moodfood-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: moodfood
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - moodfood-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - moodfood-network

networks:
  moodfood-network:
    driver: bridge

volumes:
  moodfood-data:
    driver: local