[deploy]
startCommand = "php artisan migrate --force && php artisan db:seed-safe && php artisan storage:link --force && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
